const {
    Schema,
    model,
} = require('mongoose');

const reactionSchema = new Schema({
    // creating new reaction automatically sets an objectid
    // therefore reactionId is redundant as we can utilize the autogenerated _id

    // reactionId: {
    //     type: Schema.Types.ObjectId,
    //     default: () => new Schema.Types.ObjectId
    // },
    reactionBody: {
        type: String,
        required: true,
        maxlength: 280,
    },
    username: {
        type: String,
        required: true,
    },
    createdAt: {
        type: Date,
        default: Date.now,
    }
});

const thoughtSchema = new Schema({
    thoughtText: {
        type: String,
        required: true,
        minlength: 1,
        maxlength: 280,
    },
    createdAt: {
        type: Date,
        default: Date.now,
    },
    username: {
        type: String,
        required: true,
    },
    reactions: [reactionSchema],
}, {
    toJSON: {
        virtuals: true,
        getters: true
    }
});

thoughtSchema
    .virtual('reactionCount')
    .get(function () {
        if (this.reactions) {
            return this.reactions.length;
        } else {
            return 0;
        }
    })

const Thought = model('Thought', thoughtSchema);
const Reaction = model('Reaction', reactionSchema);
module.exports = {Thought, Reaction};